version: 1
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

loggers:
  uvicorn:
    handlers: [default]
    level: INFO

  __main__:
    handlers: [default]
    level: INFO

root:
  handlers: [default]
  level: INFO
