name: Deploy FastAPI MCP Server to Azure

on:
  push:
    branches: [ ViggaBru_python_mcp ]
  pull_request:
    branches: [ ViggaBru_python_mcp ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Make startup.sh executable
      run: chmod +x startup.sh

    - name: Azure Login (Service Principal)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F27AA7646CAF48A2A5799319EC52F366 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CDC83D9F1CE14F9ABF747A282BA3C952 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EE86432984584EFA805DE15A309326A9 }}

    - name: Zip app for deployment
      run: zip -r deploy.zip . -x ".git/*" "__pycache__/*" "tests/*"

    - name: Deploy to Azure Web App (Linux)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: deploy.zip
