# name: Deploy FastAPI MCP Server to Azure

# on:
#   push:
#     branches: [ ViggaBru_python_mcp ]
#   pull_request:
#     branches: [ ViggaBru_python_mcp ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - name: Make startup.sh executable
#       run: chmod +x startup.sh

#     - name: Zip app for deployment
#       run: zip -r deploy.zip . -x ".git/*" "__pycache__/*" "tests/*"

#     - name: Deploy to Azure Web App (Linux)
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: deploy.zip

